[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "EpivirQuant"
description="EpiVirQuant directly counts and measures the size of viral-like particles, bacteria, archaea in epifluorescence microscopy images commonly used in viral ecology, viral estimation and enumeration, and microbial ecology."
authors = [
    {name = "Jose L. Figueroa III", email = "jlfiguer@charlotte.edu"},
    {name = "Sadie M. Hollenack", email = "bohllena@charlotte.edu"},
    {name = "Richard A. White III", email = "rwhit101@charlotte.edu"},
]
requires-python = ">=3.8"
dependencies = [
    "joblib",
    "configargparse",
    "matplotlib",
    "numpy",
    "scipy",
    "scikit-image",
    "pypher",
    "stardist"
]
readme = "README.MD"
dynamic = ["version"]

[project.urls]
Repository = "https://github.com/raw-lab/epivirquant"

[project.scripts]
epivirquant = "bin.epivirquant:main"    
    

[tool.setuptools]
packages = ["bin", "lib"]
package-dir = {"bin" = "bin", "lib" = "lib"} 
